import{a as v,i as l,S as q}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const S="47015635-abc1d6fc17d6df7da0f15a0aa",M="https://pixabay.com/api/";async function P(s,t=1,i=15){try{const{data:r}=await v.get(M,{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i}});return console.log(r),r.hits.length===0?{hits:[]}:r}catch(r){return console.log(r),l.error({title:"Сталася помилка при отриманні зображень.",message:"Спробуйте ще раз!",position:"topRight"}),{hits:[]}}}const u=document.querySelector(".list");function R(s){const t=s.map(({webformatURL:i,largeImageURL:r,tags:e,likes:o,views:a,comments:x,downloads:w})=>`
        <div class="gallery-item">
            <a href="${r}">
                <img src="${i}" alt="${e}" width="360" height="200"/>
            </a>
            <div class="info">
                <p class="info-text"><b class="xz">Likes:</b> ${o}</p>
                <p class="info-text"><b class="xz">Views:</b> ${a}</p>
                <p class="info-text"><b class="xz">Comments:</b> ${x}</p>
                <p class="info-text"><b class="xz">Downloads:</b> ${w}</p>
            </div>
        </div>
    `).join("");u.insertAdjacentHTML("beforeend",t)}const y=document.querySelector(".search-form"),$=document.querySelector(".search-form input"),h=document.querySelector(".loader"),n=document.querySelector(".load-more");let d,c=1,p=0,m=0,f="";n.style.display="none";y.addEventListener("submit",z);n.addEventListener("click",D);async function z(s){s.preventDefault();const t=$.value.trim();if(u.innerHTML="",t==="")return l.info({position:"topRight",title:"Помилка",message:"Заповніть поле запиту"});n.style.display="none",f=t,c=1,p=0,m=0,u.innerHTML="",b(),await g(f,c),L(),y.reset()}async function g(s,t){try{const i=await P(s,t);if(i.hits.length===0){n.style.display="none",l.info({message:"По вашому запиту нічого не знайдено!",position:"topRight"});return}p=i.totalHits,m+=i.hits.length,R(i.hits),O(),t>1&&I(),H()}catch{l.error({position:"topLeft",message:"Упс...помилка"})}}async function D(){c++,n.disabled=!0,b(),await g(f,c),L()}function b(){h.style.display="block"}function L(){h.style.display="none"}function H(){m>=p?(n.style.display="none",l.error({message:"Закінчились результати пошуку.",position:"topRight"})):(n.style.display="block",n.disabled=!1)}function O(){d?d.refresh():d=new q(".gallery-item a",{captionsData:"alt",captionDelay:250})}function I(){const s=document.querySelector(".gallery-item");if(s){const{height:t}=s.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
